spring:
  profiles:
    active: local
  servlet:
    multipart:
      location: C:/temp
      max-file-size: 100MB
      max-request-size: 100MB
  # 환경에 맞게 DB 접속정보 변경
  # DB 생성 및 초기화 sql 파일 : db_init.sql, db_user.sql
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3308/derived_resources?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: drg
    password: 123456A@
mybatis:
  type-aliases-package: com.example.drg.dto
server:
  error:
    include-exception: true
    include-stacktrace: always
    include-message: always
    include-binding-errors: always
logging:
  config: classpath:logback-spring.xml
#  level:
#    com.example.drg.dao: debug
custom:
  genFileDirPath: C:/2021/derived_resource_generator-file
  tmpDirPath: C:/temp
  logging:
    dir: log
    level: debug

---

spring:
  profiles: local
server:
  port: 8085

---

spring:
  profiles: production
  servlet:
    multipart:
      location: /tmp
  datasource:
    username: drg
    password: 123456A@
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/derived_resources?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull
custom:
  genFileDirPath: /opt/tomcat/latest/derived-resources.ml-file
  tmpDirPath: /tmp
  logging:
    dir: /tmp/derived-resources-log
    level: info